name: Build this Docker image
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: devopsansiblede/java-base:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
      - name: Trigger Build for Jira
        run: curl --request POST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" https://api.github.com/repos/devops-ansible/jira/dispatches --data '{"event_type":"build_application"}'
        
      - name: Trigger Build for Confluence
        run: curl --request POST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" https://api.github.com/repos/devops-ansible/confluence/dispatches --data '{"event_type":"build_application"}'
        
      - name: Trigger Build for Bitbucket
        run: curl --request POST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" https://api.github.com/repos/devops-ansible/bitbucket/dispatches --data '{"event_type":"build_application"}'

